
import java.util.Random;
import javax.swing.JOptionPane;
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Samuel Borjas
 */
public class JuegoGUI extends javax.swing.JFrame {

    /**
     * Creates new form JuegoGUI
     */
    public JuegoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblvida1 = new javax.swing.JLabel();
        lblvida2 = new javax.swing.JLabel();
        btnvida1 = new javax.swing.JButton();
        btnvida2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnvida11 = new javax.swing.JButton();
        btnvida12 = new javax.swing.JButton();
        btnvida21 = new javax.swing.JButton();
        btnvida22 = new javax.swing.JButton();
        barra1 = new javax.swing.JProgressBar();
        barra2 = new javax.swing.JProgressBar();
        reset = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samuel Borjas\\Documents\\NetBeansProjects\\Juego\\src\\Batman.gif")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(56, 11, 234, 345);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samuel Borjas\\Documents\\NetBeansProjects\\Juego\\src\\joker.gif")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(339, 11, 320, 345);

        lblvida1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblvida1.setForeground(new java.awt.Color(255, 255, 255));
        lblvida1.setText("100");
        getContentPane().add(lblvida1);
        lblvida1.setBounds(129, 362, 91, 26);

        lblvida2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblvida2.setForeground(new java.awt.Color(255, 255, 255));
        lblvida2.setText("100");
        getContentPane().add(lblvida2);
        lblvida2.setBounds(469, 362, 122, 26);

        btnvida1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnvida1.setText("Ataque 1");
        btnvida1.setToolTipText("");
        btnvida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvida1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnvida1);
        btnvida1.setBounds(77, 426, 99, 25);

        btnvida2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnvida2.setText("Ataque 1");
        btnvida2.setActionCommand("Ataque 1");
        btnvida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvida2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnvida2);
        btnvida2.setBounds(446, 426, 95, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VIDA: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(77, 367, 46, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VIDA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(426, 367, 37, 17);

        btnvida11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnvida11.setText("Ataque 2 ");
        btnvida11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvida11MouseClicked(evt);
            }
        });
        btnvida11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvida11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnvida11);
        btnvida11.setBounds(77, 457, 99, 25);

        btnvida12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnvida12.setText("Ataque 3");
        btnvida12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvida12MouseClicked(evt);
            }
        });
        btnvida12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvida12ActionPerformed(evt);
            }
        });
        getContentPane().add(btnvida12);
        btnvida12.setBounds(77, 488, 99, 25);

        btnvida21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnvida21.setText("Ataque 2");
        btnvida21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvida21MouseClicked(evt);
            }
        });
        btnvida21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvida21ActionPerformed(evt);
            }
        });
        getContentPane().add(btnvida21);
        btnvida21.setBounds(446, 457, 95, 25);

        btnvida22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnvida22.setText("Ataque 3");
        btnvida22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvida22MouseClicked(evt);
            }
        });
        btnvida22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvida22ActionPerformed(evt);
            }
        });
        getContentPane().add(btnvida22);
        btnvida22.setBounds(446, 488, 95, 25);

        barra1.setValue(100);
        getContentPane().add(barra1);
        barra1.setBounds(56, 394, 146, 14);

        barra2.setValue(100);
        getContentPane().add(barra2);
        barra2.setBounds(410, 394, 156, 14);

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(610, 480, 61, 23);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(610, 510, 51, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a736b5bb4dc0fb683f12a49936e83860.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 690, 560);

        setSize(new java.awt.Dimension(709, 595));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    int contador = 0;
    Random ran = new Random();
    int resp;
    Scanner lea = new Scanner(System.in);
    
   
    private void btnvida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvida1ActionPerformed
     
       int jugador2 = Integer.parseInt(lblvida2.getText()); 
       
        
     do{
  
        
        
        int ram1 = ran.nextInt(10 - 0 + 1) + 0;
        jugador2 -=ram1;
        barra2.setValue(jugador2);
        
//------------------------------------------------------------------------------ 
        
        
//------------------------------------------------------------------------------ 
        //Contador para deshabilitar boton1Player1
        
        contador = contador +1;
        if((contador >0 )&& (contador<=3)){
           btnvida2.setEnabled(true);
           btnvida21.setEnabled(true);
           btnvida22.setEnabled(true);
           btnvida1.setEnabled(false);
           btnvida11.setEnabled(false);
           btnvida12.setEnabled(false);
        }
        if(contador > 3){
            btnvida1.setEnabled(false);  
        }
//------------------------------------------------------------------------------           
          //Si el label2 llega a 0...murio!!
          if(jugador2 >0 && jugador2 <100){
            lblvida2.setText(""+jugador2);
          } 
          else{
              
            lblvida2.setText("MURIO!!!");
            btnvida1.setEnabled(false);
            btnvida11.setEnabled(false);
            btnvida12.setEnabled(false);
            btnvida2.setEnabled(false);
            btnvida21.setEnabled(false);
            btnvida22.setEnabled(false);
            JOptionPane.showMessageDialog (null, "GANO BATMAN", "GANADOR", JOptionPane.INFORMATION_MESSAGE);
          }  
            
     }while(jugador2 == 0 );
                
 
//------------------------------------------------------------------------------
       
    }//GEN-LAST:event_btnvida1ActionPerformed
    
    int contador1 = 0;
    private void btnvida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvida2ActionPerformed
        
        int jugador1 = Integer.parseInt(lblvida1.getText());
    do{
        int ram2 = ran.nextInt(10 - 0 + 1) + 0;
        
       jugador1 -=ram2;
       barra1.setValue(jugador1);
       
//------------------------------------------------------------------------------
       //Contador para deshabilitar boton1Player2
       contador1 = contador1 +1;
        
        if((contador1 >0 )&& (contador1<3)){
           btnvida1.setEnabled(true);
           btnvida11.setEnabled(true);
           btnvida12.setEnabled(true);
           btnvida2.setEnabled(false);
           btnvida21.setEnabled(false);
           btnvida22.setEnabled(false);
        }
        if(contador1 >= 3){
            btnvida2.setEnabled(false);  
        }
 //-----------------------------------------------------------------------------      
        // Si el valor del label llega a 0...Murio!! 
        if(jugador1 >0 && jugador1 <=100){
            lblvida1.setText(""+jugador1);
        }
        else{
            
            lblvida1.setText("MURIO!!!");
            btnvida1.setEnabled(false);
            btnvida11.setEnabled(false);
            btnvida12.setEnabled(false);
            btnvida2.setEnabled(false);
            btnvida21.setEnabled(false);
            btnvida22.setEnabled(false);
            JOptionPane.showMessageDialog (null, "GANO JOKER", "GANADOR", JOptionPane.INFORMATION_MESSAGE); 
            
        }
    }while(jugador1 == 0);

 //-----------------------------------------------------------------------------
       
    }//GEN-LAST:event_btnvida2ActionPerformed
   
//////////////////////////////////////////////////////////////////////////////// 
    private void btnvida11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvida11MouseClicked
     // NO   
    }//GEN-LAST:event_btnvida11MouseClicked
   
    private void btnvida21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvida21MouseClicked
       //NO
    }//GEN-LAST:event_btnvida21MouseClicked

    private void btnvida12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvida12MouseClicked
        //NO
    }//GEN-LAST:event_btnvida12MouseClicked

    private void btnvida22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvida22MouseClicked
        //NO
    }//GEN-LAST:event_btnvida22MouseClicked
////////////////////////////////////////////////////////////////////////////////
    int cont = 0;
   
    private void btnvida11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvida11ActionPerformed
       int juga2 = Integer.parseInt(lblvida2.getText());
    do{
        int rand = ran.nextInt(50 - 11 + 1) + 11;
         juga2 -=rand;
         barra2.setValue(juga2);
//------------------------------------------------------------------------------ 
        //Contador para deshabilitar boton2Player1
        cont = cont +1;
        
        if((cont >0 )&& (cont<=2)){
           btnvida2.setEnabled(true);
           btnvida21.setEnabled(true);
           btnvida22.setEnabled(true);
           btnvida1.setEnabled(false);
           btnvida11.setEnabled(false);
           btnvida12.setEnabled(false);
        }
        
        if(cont > 2){
            btnvida11.setEnabled(false);   
        }
//------------------------------------------------------------------------------
        
       if(juga2 > 0 && juga2 <=100){
       lblvida2.setText(""+juga2);
       }
       else{
             
            lblvida2.setText("MURIO!!!");
            btnvida1.setEnabled(false);
            btnvida11.setEnabled(false);
            btnvida12.setEnabled(false);
            btnvida2.setEnabled(false);
            btnvida21.setEnabled(false);
            btnvida22.setEnabled(false);
            JOptionPane.showMessageDialog (null, "GANO BATMAN", "GANADOR", JOptionPane.INFORMATION_MESSAGE);
       }
    }while(juga2 == 0);
//------------------------------------------------------------------------------
    }//GEN-LAST:event_btnvida11ActionPerformed
    
    int cont1 = 0;
    private void btnvida21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvida21ActionPerformed
        
        int jugad2 = Integer.parseInt(lblvida1.getText());
    do{
        int rand1 = ran.nextInt(50 - 11 + 1 )+ 11;
        jugad2 -=rand1;
        barra1.setValue(jugad2);
//------------------------------------------------------------------------------
      //Contador para deshabilitar boton2Player2
        cont1 = cont1 +1;
        
        if((cont1 >0 )&& (cont1<2)){
           btnvida1.setEnabled(true);
           btnvida11.setEnabled(true);
           btnvida12.setEnabled(true);
           btnvida2.setEnabled(false);
           btnvida21.setEnabled(false);
           btnvida22.setEnabled(false);
        }
        if(cont1 >= 2){
            btnvida21.setEnabled(false);   
        }
//------------------------------------------------------------------------------
        
       if(jugad2 > 0 && jugad2 <= 100){
        lblvida1.setText(""+jugad2);
       }
       else{
            
         lblvida1.setText("MURIO!!!");
         btnvida1.setEnabled(false);
         btnvida11.setEnabled(false);
         btnvida12.setEnabled(false);
         btnvida2.setEnabled(false);
         btnvida21.setEnabled(false);
         btnvida22.setEnabled(false);
         JOptionPane.showMessageDialog (null, "GANO JOKER", "GANADOR", JOptionPane.INFORMATION_MESSAGE);
         
       }
    }while(jugad2 == 0);
//------------------------------------------------------------------------------         
    }//GEN-LAST:event_btnvida21ActionPerformed
    
    int x = 0;
    private void btnvida12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvida12ActionPerformed

//------------------------------------------------------------------------------        
        int jugado1 = Integer.parseInt(lblvida2.getText());
        
    do{
        int rando1 = ran.nextInt(90 - 51 + 1)+ 51;
        jugado1 -=rando1;
        barra2.setValue(jugado1);
//------------------------------------------------------------------------------ 
        //Contador para deshabilitar boton3Player1
        x = x +1;
        
        if((x >0 )&& (x<1)){
           btnvida1.setEnabled(false);
           btnvida11.setEnabled(false);
           btnvida12.setEnabled(false);
           
            btnvida2.setEnabled(true);
           btnvida21.setEnabled(true);
           btnvida22.setEnabled(true);
        }
        if(x > 1){
            btnvida12.setEnabled(false);   
        }
//------------------------------------------------------------------------------
        if(jugado1 > 0 && jugado1 <=100){
            lblvida2.setText(""+jugado1);
        }
        else{    
         lblvida2.setText("MURIO!!!");
         btnvida1.setEnabled(false);
         btnvida11.setEnabled(false);
         btnvida12.setEnabled(false);
         btnvida2.setEnabled(false);
         btnvida21.setEnabled(false);
         btnvida22.setEnabled(false);
         JOptionPane.showMessageDialog (null, "GANO BATMAN", "GANADOR", JOptionPane.INFORMATION_MESSAGE);
        }
    }while(jugado1 ==0);
//------------------------------------------------------------------------------        
        
    }//GEN-LAST:event_btnvida12ActionPerformed

    int y = 0;
    private void btnvida22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvida22ActionPerformed
        
        int jugado2 = Integer.parseInt(lblvida1.getText());
    do{
        int rando2 = ran.nextInt(90 - 51 + 1 )+ 51;
        jugado2 -= rando2;
        barra1.setValue(jugado2);
//------------------------------------------------------------------------------ 
        //Contador para deshabilitar boton3Player2
        y = y +1;
        
        if((y >0 )&& (y<1)){
            
           btnvida1.setEnabled(true);
           btnvida11.setEnabled(true);
           btnvida12.setEnabled(true);
           
           btnvida2.setEnabled(false);
           btnvida21.setEnabled(false);
           btnvida22.setEnabled(false);
        }
        if(y >= 1){
            btnvida22.setEnabled(false);   
        }
//------------------------------------------------------------------------------
        if(jugado2 >0 && jugado2 <= 100){
            lblvida1.setText(""+jugado2);
        }
        else{   
         lblvida1.setText("MURIO!!!");
         btnvida1.setEnabled(false);
         btnvida11.setEnabled(false);
         btnvida12.setEnabled(false);
         btnvida2.setEnabled(false);
         btnvida21.setEnabled(false);
         btnvida22.setEnabled(false);
         JOptionPane.showMessageDialog (null, "GANO JOKER", "GANADOR", JOptionPane.INFORMATION_MESSAGE);
        }
    }while(jugado2 == 0 );
        
//------------------------------------------------------------------------------ 
    }//GEN-LAST:event_btnvida22ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        
        lblvida1.setText("100");
        lblvida2.setText("100");
        barra1.setValue(100);
        barra2.setValue(100);
        
            btnvida1.setEnabled(true);
            btnvida11.setEnabled(true);
            btnvida12.setEnabled(true);
            
        btnvida2.setEnabled(true);
        btnvida21.setEnabled(true);
        btnvida22.setEnabled(true);
        
        
    }//GEN-LAST:event_resetActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JuegoGUI().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra1;
    private javax.swing.JProgressBar barra2;
    private javax.swing.JButton btnvida1;
    private javax.swing.JButton btnvida11;
    private javax.swing.JButton btnvida12;
    private javax.swing.JButton btnvida2;
    private javax.swing.JButton btnvida21;
    private javax.swing.JButton btnvida22;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblvida1;
    private javax.swing.JLabel lblvida2;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables


}
